core/cart/urls.py
from django.urls import path, re_path
from .views import *

app_name = "cart"

urlpatterns = [
    path(
        "session/add-product/",
        SessionAddProductView.as_view(),
        name="session-add-product",
    ),
    path(
        "session/remove-product/",
        SessionRemoveProductView.as_view(),
        name="session-remove-product",
    ),
    path(
        "session/update-product-quantity/",
        SessionUpdateProductQuantityView.as_view(),
        name="session-update-product-quantity",
    ),
    path("summary/", CartSummaryView.as_view(), name="cart-summary"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("review/", include("review.urls")),
    
    
]

if settings.DEBUG is True:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

core/shop/urls.py
from django.urls import path, re_path
from .views import *

app_name = "shop"

urlpatterns = [
    path("product/grid/", ShopProductGridView.as_view(), name="product-grid"),
    re_path(
        r"product/(?P<slug>[-\w]+)/detail/",
        ShopProductDetailView.as_view(),
        name="product-detail",
    ),
    path(
        "add-or-remove-wishlist/",
        AddOrRemoveWishlistView.as_view(),
        name="add-or-remove-wishlist",
    ),
]

core/shop/models.py
from django.db import models
from django.utils.functional import cached_property


class ProductStatusType(models.IntegerChoices):
    publish = 1, ("نمایش")
    draft = 2, ("عدم نمایش")


class ProductCategoryModel(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ProductModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.PROTECT)
    category = models.ManyToManyField(ProductCategoryModel)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    image = models.ImageField(
        default="/default/product-image.png", upload_to="product/img/"
    )
    description = models.TextField()
    brief_description = models.TextField(blank=True, null=True)
    stock = models.IntegerField(default=0)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=0)
    discount_percent = models.IntegerField(default=0)
    status = models.IntegerField(
        choices=ProductStatusType.choices, default=ProductStatusType.draft.value
    )

    avg = models.FloatField(default=0.0)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:

        ordering = ["-created_date"]

    def __str__(self):
        return self.title

    def is_discounted(self):
        return self.discount_percent > 0

    def get_price(self):
        if self.is_discounted():
            discount = self.price * self.discount_percent / 100
            return round(self.price - discount)
        return round(self.price)

    def get_show_price(self):
        if self.is_discounted():
            return f"{self.get_price()} تومان <span class='text-muted text-decoration-line-through'>{self.price} تومان</span>"
        return f"{self.get_price()} تومان"

    def is_published(self):
        return self.status == ProductStatusType.publish.value


class ProductImageModel(models.Model):
    product = models.ForeignKey(ProductModel,on_delete=models.CASCADE,related_name="product_images")
    file = models.ImageField(upload_to="product/extra-img/")
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-created_date"]


class WishlistProductModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.PROTECT)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.title

core/dashboard/admin/forms/products.py
from django import forms
from shop.models import *


class ProductForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = [
            "category",
            "title",
            "slug",
            "image",
            "description",
            "price",
            "status",
            "brief_description",
            "stock",
            "discount_percent",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs["class"] = "form-control"
        self.fields["slug"].widget.attrs["class"] = "form-control"
        self.fields["category"].widget.attrs["class"] = "form-control"
        self.fields["image"].widget.attrs["class"] = "form-control"
        self.fields["brief_description"].widget.attrs["class"] = "form-control"
        self.fields["description"].widget.attrs["id"] = "ckeditor"
        self.fields["stock"].widget.attrs["class"] = "form-control"
        self.fields["stock"].widget.attrs["type"] = "number"
        self.fields["status"].widget.attrs["class"] = "form-select"
        self.fields["price"].widget.attrs["class"] = "form-control"
        self.fields["discount_percent"].widget.attrs["class"] = "form-control"

core/dashboard/admin/views/products.py
from django.views.generic import (
    View,
    TemplateView,
    UpdateView,
    ListView,
    DetailView,
    DeleteView,
    CreateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.permissions import HasAdminAccessPermission
from django.contrib.auth import views as auth_views
from dashboard.admin.forms import *
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from accounts.models import Profile
from django.shortcuts import redirect
from django.contrib import messages
from django.core.exceptions import FieldError
from ..forms import *

from shop.models import *


class AdminProductListView(LoginRequiredMixin, HasAdminAccessPermission, ListView):
    template_name = "dashboard/admin/products/products-list.html"
    paginate_by = 10

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)

    def get_queryset(self):
        queryset = ProductModel.objects.all()
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(title__icontains=search_q)
        if category_id := self.request.GET.get("category_id"):
            queryset = queryset.filter(category__id=category_id)
        if min_price := self.request.GET.get("min_price"):
            queryset = queryset.filter(price__gte=min_price)
        if max_price := self.request.GET.get("max_price"):
            queryset = queryset.filter(price__lte=max_price)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except FieldError:
                pass
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()

        context["total_items"] = queryset.count()
        context["categories"] = ProductCategoryModel.objects.filter(
            productmodel__in=queryset
        ).distinct()

        return context


class AdminProductCreateView(
    LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, CreateView
):
    template_name = "dashboard/admin/products/product-create.html"
    queryset = ProductModel.objects.all()
    form_class = ProductForm
    success_message = "محصول با موفقیت ایجاد شد."

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("dashboard:admin:product-list")


class AdminProductUpdateView(
    LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, UpdateView
):
    template_name = "dashboard/admin/products/product-edit.html"
    queryset = ProductModel.objects.all()
    form_class = ProductForm
    success_message = "محصول با موفقیت ویرایش شد."

    def get_success_url(self):
        return reverse_lazy(
            "dashboard:admin:product-edit", kwargs={"pk": self.get_object().pk}
        )


class AdminProductDeleteView(
    LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, DeleteView
):
    template_name = "dashboard/admin/products/product-delete.html"
    queryset = ProductModel.objects.all()
    success_url = reverse_lazy("dashboard:admin:product-list")
    success_message = "محصول با موفقیت حذف شد."

core/templates/dashboard/admin/products/product-create.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}


{% block extra_css %}
<style>
    .small-primary-button {
        padding: 3px 10px;
        background-color: #007bff;
        color: white;
        border: none;
        cursor: pointer;
        font-size: 10px;
        border-radius: 5px;
    }

    .small-primary-button:hover,
    .small-primary-button:focus {
        background-color: #0056b3;
    }
</style>

{% endblock %}



{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light mb-0">
        <li class="breadcrumb-item">حساب</li>
        <li class="breadcrumb-item">داشبورد ادمین</li>
        <li class="breadcrumb-item">محصولات</li>
        <li class="breadcrumb-item active" aria-current="page">
            ایجاد محصول
        </li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
        <h5 class="card-header-title">ایجاد محصول</h5>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-body">
            <div class="row d-flex ">
                <div class="col-md-6 mb-3">
                    <label>نام محصول</label>
                    {{form.title}}
                </div>
                <div class="col-md-6 mb-3">
                    <label>slug محصول - <button class="small-primary-button" type="button" onclick="generateSlug()">ساخت
                            slug</button> </label>
                    {{form.slug}}
                </div>
                <div class="col-md-6 mb-3">
                    <label>تعداد</label>
                    {{form.stock}}
                </div>

                <div class="col-md-6 mb-3">
                    <label>وضعیت</label>
                    {{form.status}}
                </div>
                <div class="col-md-6 mb-3">
                    <label>دسته بندی</label>
                    {{form.category}}
                </div>
                <div class="col-md-4 mb-3">
                    <label>قیمت</label>
                    {{form.price}}
                </div>
                <div class="col-md-2 mb-3">
                    <label>درصد تخفیف</label>
                    {{form.discount_percent}}
                </div>

                <div class="col-md-12 mb-3">
                    <label>توضیح کوتاه</label>
                    {{form.brief_description}}
                </div>
                <div class="col-md-12 mb-3">
                    <label>توضیحات</label>
                    {{form.description}}
                </div>

                <div class="col-md-12 mb-3">
                    <label for="validationValidFileInput1">تصویر محصول</label>
                    {{form.image}}
                </div>


            </div>
            <div class="card-footer">
                <div class=" d-flex pt-5 justify-content-end">
                    <a class="btn btn-secondary ms-3" href="{% url 'dashboard:admin:product-list' %}">بازگشت</a>
                    <button class="btn btn-primary ms-3" type="submit">ایجاد محصول</button>
                </div>
            </div>
    </form>
</div>

{% endblock %}

{% block extra_js %}
<script>

    function generateSlug() {
        const title = $("#id_title").val();
        const slug = slugify(title);
        $("#id_slug").val(slug)
    }

    function slugify(titleStr) {
        titleStr = titleStr.replace(/^\s+|\s+$/g, '');
        titleStr = titleStr.toLowerCase();
        //persian support
        titleStr = titleStr.replace(/[^a-z0-9_\s-ءاأإآؤئبتثجحخدذرزسشصضطظعغفقكلمنهويةى]#u/, '')
            // Collapse whitespace and replace by -
            .replace(/\s+/g, '-')
            // Collapse dashes
            .replace(/-+/g, '-');
        slugStr = titleStr;
        return slugStr;
    }
</script>
{% endblock %}

{% block extra_js_no_compress %}
<script src="{% static 'vendor/ckeditor/ckeditor.js' %}"></script>
<script>
    // Replace 'editor' with the id of your textarea
    CKEDITOR.replace('ckeditor');
</script>
{% endblock %}

core/templates/dashboard/admin/products/product-delete.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light mb-0">
        <li class="breadcrumb-item">حساب</li>
        <li class="breadcrumb-item">داشبورد ادمین</li>
        <li class="breadcrumb-item">محصولات</li>
        <li class="breadcrumb-item active" aria-current="page">
            حذف محصول
        </li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
        <h5 class="card-header-title">حذف محصول</h5>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <form action="." method="post">
        {% csrf_token %}
        <div class="card-body">
            <div class="row d-flex ">
                <p> آیا از حذف محصول زیر اطمینان دارید؟</p>
                <div class="row">
                    <span>شناسه محصول : {{object.pk}}</span>
                    <span>نام محصول : {{object.title}}</span>
                </div>

            </div>
            <div class="card-footer">
                <div class=" d-flex pt-5 justify-content-end">
                    <button type="submit" class="btn btn-danger ms-3">تایید حذف</button>
                    <a class="btn btn-secondary ms-3"
                        href="{% url 'dashboard:admin:product-edit' pk=object.pk %}">بازگشت</a>
                </div>
            </div>
    </form>
</div>

{% endblock %}

core/templates/dashboard/admin/products/product-edit.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}


{% block extra_css %}
<style>
    .small-primary-button {
        padding: 3px 10px;
        background-color: #007bff;
        color: white;
        border: none;
        cursor: pointer;
        font-size: 10px;
        border-radius: 5px;
    }

    .small-primary-button:hover,
    .small-primary-button:focus {
        background-color: #0056b3;
    }
</style>
{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light mb-0">
        <li class="breadcrumb-item">حساب</li>
        <li class="breadcrumb-item">داشبورد ادمین</li>
        <li class="breadcrumb-item">محصولات</li>
        <li class="breadcrumb-item active" aria-current="page">
            ویرایش محصول
        </li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="row">
    <div>
        <div class="card mb-5">
            <!-- Header -->
            <div class="card-header border-bottom d-flex justify-content-between align-items-center">
                <h5 class="card-header-title">ویرایش محصول</h5>
                {% if object.is_published %}
                <a class="btn btn-sm btn-primary" target="_blank"
                    href="{% url 'shop:product-detail' slug=object.slug %}">نمایش
                    محصول</a>
                {% endif %}
            </div>
            <!-- End Header -->

            <!-- Body -->
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                    <div class="row d-flex ">
                        <div class="col-md-6 mb-3">
                            <label>نام محصول</label>
                            {{form.title}}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label>slug محصول - <button class="small-primary-button" type="button"
                                    onclick="generateSlug()">ساخت
                                    slug</button> </label>
                            {{form.slug}}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label>تعداد</label>
                            {{form.stock}}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label>وضعیت</label>
                            {{form.status}}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label>دسته بندی</label>
                            {{form.category}}
                        </div>
                        <div class="col-md-4 mb-3">
                            <label>قیمت</label>
                            {{form.price}}
                        </div>
                        <div class="col-md-2 mb-3">
                            <label>درصد تخفیف</label>
                            {{form.discount_percent}}
                        </div>

                        <div class="col-md-12 mb-3">
                            <label>توضیح کوتاه</label>
                            {{form.brief_description}}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label>توضیحات</label>
                            {{form.description}}
                        </div>

                        <div class="col-md-12 mb-3">
                            <label for="validationValidFileInput1">تصویر محصول</label>
                            {{form.image}}
                        </div>


                    </div>
                    <div class="card-footer">
                        <div class=" d-flex pt-5 justify-content-end">
                            <a class="btn btn-danger ms-3"
                                href="{% url 'dashboard:admin:product-delete' pk=object.pk %}">حذف</a>
                            <a class="btn btn-secondary ms-3" href="{% url 'dashboard:admin:product-list' %}">بازگشت</a>
                            <button class="btn btn-primary ms-3" type="submit">ثبت تغییرات</button>
                        </div>
                    </div>
            </form>
        </div>
    </div>
    <div>
        <div class="card">
            <!-- Header -->
            <div class="card-header border-bottom d-flex justify-content-between align-items-center">
                <h5 class="card-header-title">ویرایش تصاویر بیشتر</h5>
            </div>
            <!-- End Header -->

            <!-- Body -->
            <form action="#}" method="post" enctype="multipart/form-data">

                {% csrf_token %}
                <div class="card-body">
                    <div class="row d-flex align-items-center">
                        <div class="col-md-9 mb-3 d-flex align-items-center">
                            <label>تصویر محصول</label>
                            {{image_form.file}}
                        </div>
                        <div class="col-md-3 mb-3">
                            <button class="btn btn-primary ms-3" type="submit">ثبت تصویر</button>
                        </div>
                    </div>
                </div>


            </form>

            <div class="card-body">
                <div class="row d-flex ">
                    {% for product_image in object.product_images.all %}
                    <div class="col-md-2">
                        <img class="img-fluid" style="width:100px; height:100px" src="{{product_image.file.url}}"
                            alt="Image Description">
                        <form
                            action="{% url 'dashboard:admin:product-remove-image' pk=object.pk image_id=product_image.pk %}"
                            method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">حذف تصویر</button>
                        </form>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script>

    function generateSlug() {
        const title = $("#id_title").val();
        const slug = slugify(title);
        $("#id_slug").val(slug)
    }

    function slugify(titleStr) {
        titleStr = titleStr.replace(/^\s+|\s+$/g, '');
        titleStr = titleStr.toLowerCase();
        //persian support
        titleStr = titleStr.replace(/[^a-z0-9_\s-ءاأإآؤئبتثجحخدذرزسشصضطظعغفقكلمنهويةى]#u/, '')
            // Collapse whitespace and replace by -
            .replace(/\s+/g, '-')
            // Collapse dashes
            .replace(/-+/g, '-');
        slugStr = titleStr;
        return slugStr;
    }
</script>
{% endblock %}

{% block extra_js_no_compress %}
<!-- Load CKEditor 5 Classic LTS version -->
<script src="https://cdn.ckeditor.com/4.25.1/standard/ckeditor.js"></script>
<script>
    // Replace 'editor' with the id of your textarea
    CKEDITOR.replace('ckeditor');
</script>

{% endblock %}

core/templates/dashboard/admin/products/products-list.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light mb-0">
        <li class="breadcrumb-item">حساب</li>
        <li class="breadcrumb-item">داشبورد ادمین</li>
        <li class="breadcrumb-item active" aria-current="page">
            محصولات
        </li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<!-- Card -->
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
        <div class="d-flex justify-content-between align-items-center">
            <h5 class="">لیست محصولات</h5>
            <a class="btn btn-primary" href="{% url 'dashboard:admin:product-create' %}">ایجاد محصول</a>
        </div>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <div class="card-body">

        <div class="container pb-5">
            <form action="." class="row">

                <!-- Input Card -->
                <div class="col-md-3 py-1">
                    <input type="text" class="form-control form-control-sm" placeholder="جستو جوی کالا" name="q"
                        id="search-query-filter">

                </div>
                <!-- End Input Card -->
                <div class="col-md-3 py-1">
                    <select class="form-select form-select-sm" name="category_id" id="category-id-filter">
                        <option value="" selected>دسته بندی</option>
                        {% for category in categories %}
                        <option value="{{category.id}}">{{category.title}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-3 py-1">
                    <select class="form-select form-select-sm" id="order-by-filter">
                        <option value="" selected>مرتب سازی</option>
                        <option value="-created_date">جدیدترین</option>
                        <option value="created_date">قدیمی ترین</option>
                        <option value="-price">بیشترین قیمت</option>
                        <option value="price">کمترین قیمت</option>
                    </select>
                </div>

                <div class="col-md-2 py-1">
                    <select class="form-select form-select-sm" id="page-size-filter">
                        <option value="" selected>تعداد</option>
                        <option value="5">5</option>
                        <option value="10">10</option>
                        <option value="20">20</option>
                        <option value="30">30</option>
                        <option value="50">50</option>
                    </select>
                </div>

                <div class="col-md-1 py-1">
                    <button type="submit" class="btn btn-sm btn-icon btn-primary btn-search"><i
                            class="bi-search"></i></button>
                </div>
            </form>

        </div>

        <div class="row">

            <!-- Table -->
            <div class="table-responsive">
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">نام محصول</th>
                            <th scope="col">دسته بندی</th>
                            <th scope="col">قیمت</th>
                            <th scope="col">تعداد</th>
                            <th scope="col">وضعیت</th>
                            <th scope="col">تخفیف</th>
                            <th scope="col">عملیات</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr>
                            <th scope="row">{{object.id}}</th>
                            <td>{{object.title}}</td>
                            <td>{% for category in object.category.all %} {{category.title}}
                                {% if not forloop.last %},{% endif %} {% endfor %}</td>
                            <td>{{object.price}}</td>
                            <td>{{object.stock}}</td>
                            <td> {% if object.is_published %}<span class="badge bg-success">نشر شده</span>
                                {% else %}
                                <span class="badge bg-danger">ذخیره</span> {% endif %}
                            </td>
                            <td>%{{ object.discount_percent}}</td>
                            <td class="d-flex">
                                <a class="btn btn-sm btn-icon btn-ghost-secondary"
                                    href="{% url 'dashboard:admin:product-edit' pk=object.pk %}"><i
                                        class="bi-pencil-square"></i></a>

                                {% if object.is_published %}
                                <a class="btn btn-sm btn-icon btn-ghost-primary" target="_blank"
                                    href="{% url 'shop:product-detail' slug=object.slug %}"><i class="bi-eye"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
            <!-- End Table -->
            <div class="row m-1 py-0 ">
                <div class="d-flex justify-content-start">
                    <div>
                        {{total_items}} محصول
                    </div>


                </div>
            </div>

            <!-- Pagination -->

            <div class="row pt-5 mt-3">
                {% if page_obj.has_other_pages %}
                <!-- Pagination -->
                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <button class="page-link" onclick="changePage(`{{ page_obj.previous_page_number }}`)"
                                aria-label="Previous">
                                <span aria-hidden="true">
                                    <i class="bi-chevron-double-right small"></i>
                                </span>
                            </button>
                        </li>
                        {% endif %}
                        {{page_obj.page_range}}
                        {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                        {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %} <li class="page-item">
                            <button class="page-link" onclick="changePage(`{{i}}`)">{{ i }}</button></li>

                            {% endif %}

                            {% endfor %}


                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <button class="page-link" onclick="changePage(`{{ page_obj.next_page_number }}`)"
                                    aria-label="Previous">
                                    <span aria-hidden="true">
                                        <i class="bi-chevron-double-left small"></i>
                                    </span>
                                </button>
                            </li>
                            {% endif %}

                    </ul>
                </nav>
                {% endif %}
                <!-- End Pagination -->
            </div>
            <!-- End Pagination -->



        </div>
        <!-- End Row -->

    </div>
    <!-- End Body -->
</div>
<!-- End Card -->
{% endblock %}


{% block extra_js %}
<script>

    $(document).ready(function () {
        let current_url_params = new URLSearchParams(window.location.search)
        $("#page-size-filter").val(current_url_params.get("page_size") || "10")
        $("#order-by-filter").val(current_url_params.get("order_by") || "")
        $("#search-query-filter").val(current_url_params.get("q") || "")
        $("#min-price-filter").val(current_url_params.get("min_price") || "")
        $("#max-price-filter").val(current_url_params.get("max_price") || "")
        $("#category-id-filter").val(current_url_params.get("category_id") || "")

    });
    $('#page-size-filter').change(function () {
        let current_url_params = new URLSearchParams(window.location.search)
        var selectedOption = $(this).val();
        current_url_params.set("page_size", selectedOption)
        let new_url = window.location.pathname + "?" + current_url_params.toString()
        window.location.href = new_url
    });
    $('#order-by-filter').change(function () {
        let current_url_params = new URLSearchParams(window.location.search)
        var selectedOption = $(this).val();
        current_url_params.set("order_by", selectedOption)
        let new_url = window.location.pathname + "?" + current_url_params.toString()
        window.location.href = new_url
    });

</script>
{% endblock %}